# Generated by Django 4.2 on 2023-04-13 18:22
"""Файл миграций"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Миграции - это способ Django распространять изменения,
       которые вы вносите в свои модели (добавление поля, удаление модели и т.д.),
       в схему вашей базы данных.
       Они разработаны, чтобы быть в основном автоматическими"""
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(unique=True)),
                ('passport', models.BigIntegerField(max_length=10, unique=True)),
                ('fio', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField(null=True, unique=True)),
                ('amount_of_funds', models.IntegerField(default=0)),
                ('account_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='bank.userdata')),
            ],
        ),
    ]
