# Generated by Django 4.2 on 2023-05-22 12:09
"""Миграции"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """2"""
    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='block',
            field=models.BooleanField(default=0),
        ),
    ]
