# Generated by Django 4.2 on 2023-04-15 15:32
"""Файл миграций"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """Может в гитигнор кинуть?"""
    dependencies = [
        ('bank', '0002_alter_transfer_recipient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='passport',
            field=models.IntegerField(unique=True),
        ),
    ]
